# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/xiuye/application/cmake-3.17.3-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/xiuye/application/cmake-3.17.3-Linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xiuye/programming/cpp/NtyCo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xiuye/programming/cpp/NtyCo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/xiuye/application/cmake-3.17.3-Linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/xiuye/application/cmake-3.17.3-Linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xiuye/programming/cpp/NtyCo/CMakeFiles /home/xiuye/programming/cpp/NtyCo/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xiuye/programming/cpp/NtyCo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nty_core

# Build rule for target.
nty_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nty_core
.PHONY : nty_core

# fast build rule for target.
nty_core/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/nty_core.dir/build.make core/CMakeFiles/nty_core.dir/build
.PHONY : nty_core/fast

#=============================================================================
# Target rules for targets named nty_http_server

# Build rule for target.
nty_http_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nty_http_server
.PHONY : nty_http_server

# fast build rule for target.
nty_http_server/fast:
	$(MAKE) $(MAKESILENT) -f sample/CMakeFiles/nty_http_server.dir/build.make sample/CMakeFiles/nty_http_server.dir/build
.PHONY : nty_http_server/fast

#=============================================================================
# Target rules for targets named nty_client

# Build rule for target.
nty_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nty_client
.PHONY : nty_client

# fast build rule for target.
nty_client/fast:
	$(MAKE) $(MAKESILENT) -f sample/CMakeFiles/nty_client.dir/build.make sample/CMakeFiles/nty_client.dir/build
.PHONY : nty_client/fast

#=============================================================================
# Target rules for targets named nty_http_epoll

# Build rule for target.
nty_http_epoll: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nty_http_epoll
.PHONY : nty_http_epoll

# fast build rule for target.
nty_http_epoll/fast:
	$(MAKE) $(MAKESILENT) -f sample/CMakeFiles/nty_http_epoll.dir/build.make sample/CMakeFiles/nty_http_epoll.dir/build
.PHONY : nty_http_epoll/fast

#=============================================================================
# Target rules for targets named nty_bench

# Build rule for target.
nty_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nty_bench
.PHONY : nty_bench

# fast build rule for target.
nty_bench/fast:
	$(MAKE) $(MAKESILENT) -f sample/CMakeFiles/nty_bench.dir/build.make sample/CMakeFiles/nty_bench.dir/build
.PHONY : nty_bench/fast

#=============================================================================
# Target rules for targets named nty_server

# Build rule for target.
nty_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nty_server
.PHONY : nty_server

# fast build rule for target.
nty_server/fast:
	$(MAKE) $(MAKESILENT) -f sample/CMakeFiles/nty_server.dir/build.make sample/CMakeFiles/nty_server.dir/build
.PHONY : nty_server/fast

#=============================================================================
# Target rules for targets named nty_websocket_server

# Build rule for target.
nty_websocket_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nty_websocket_server
.PHONY : nty_websocket_server

# fast build rule for target.
nty_websocket_server/fast:
	$(MAKE) $(MAKESILENT) -f sample/CMakeFiles/nty_websocket_server.dir/build.make sample/CMakeFiles/nty_websocket_server.dir/build
.PHONY : nty_websocket_server/fast

#=============================================================================
# Target rules for targets named nty_http_server_mulcore

# Build rule for target.
nty_http_server_mulcore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nty_http_server_mulcore
.PHONY : nty_http_server_mulcore

# fast build rule for target.
nty_http_server_mulcore/fast:
	$(MAKE) $(MAKESILENT) -f sample/CMakeFiles/nty_http_server_mulcore.dir/build.make sample/CMakeFiles/nty_http_server_mulcore.dir/build
.PHONY : nty_http_server_mulcore/fast

#=============================================================================
# Target rules for targets named nty_server_mulcore

# Build rule for target.
nty_server_mulcore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nty_server_mulcore
.PHONY : nty_server_mulcore

# fast build rule for target.
nty_server_mulcore/fast:
	$(MAKE) $(MAKESILENT) -f sample/CMakeFiles/nty_server_mulcore.dir/build.make sample/CMakeFiles/nty_server_mulcore.dir/build
.PHONY : nty_server_mulcore/fast

#=============================================================================
# Target rules for targets named ntyco_httpd

# Build rule for target.
ntyco_httpd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ntyco_httpd
.PHONY : ntyco_httpd

# fast build rule for target.
ntyco_httpd/fast:
	$(MAKE) $(MAKESILENT) -f sample/CMakeFiles/ntyco_httpd.dir/build.make sample/CMakeFiles/ntyco_httpd.dir/build
.PHONY : ntyco_httpd/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nty_bench"
	@echo "... nty_client"
	@echo "... nty_core"
	@echo "... nty_http_epoll"
	@echo "... nty_http_server"
	@echo "... nty_http_server_mulcore"
	@echo "... nty_server"
	@echo "... nty_server_mulcore"
	@echo "... nty_websocket_server"
	@echo "... ntyco_httpd"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

